; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:black_f407ve]
platform = ststm32
board = black_f407ve
framework = stm32cube

extra_scripts = pre:setup_cubemx_env_auto.py
platform_packages = toolchain-gccarmnoneeabi@1.120301.0
; The name of the library directory in which the linked resources will

; be placed

lib_deps = 
	STLinkedResources
	STM32_USB_Device_Library
	ArduinoBackport

	
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_STANDARD_LIB
